### ISSUE TITLE
Use local database

### ISSUE THREAD

**Issue by kamieniarz** [muckelba/PogoStats#8]
Is there a way to store all data in local database instead of running database in docker container?

**Comment by kamieniarz** [comment]
I tried to remove `database` section from yml file. I also changed function grafana_sql to look more like function scanner_sql but I changed params to match these from first lines from .env file and I also added MYSQL_HOST but honestly I don't know what I'm doing and thing is not working... I mean grafana can't establish connection with my local database which I created using dump from docker database

**Comment by Emil007** [comment]
I have exactly the same problem right now :D
Since i was running three seperate databases, i tried to consolidate, but i'm not able to connect to anything except the one in the container :(

**Comment by muckelba** [comment]
The problem is that there's no easy way to access running services on the hostsystem from the container (either app or grafana). I've solved it for the app container by using a socketfile (see README), you could probably do the same for grafana but at this point you could just host everything natively without any docker stuff.
This whole project is designed to just work out of the box with a very tight integration between the containers. Ripping out only some components and transforming it into a frankenstein setup does not really make sense to me to be honest.
